---
- name: (CentOS) Install GeoIP EPEL dependency
  ansible.builtin.yum:
    name: epel-release
  when:
    - ansible_facts['distribution'] == "CentOS"
    - '"geoip" in nginx_modules'
    - nginx_install_epel_release | bool

- name: (RHEL 7) Install GeoIP2 dependency
  when:
    - ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] is version('7', '==')
    - '"geoip2" in nginx_modules'
  block:
    - name: (RHEL 7) Check if libmaxminddb is available
      ansible.builtin.yum:
        list: available
      register: packages

    - name: (RHEL 7) Install libmaxminddb
      ansible.builtin.yum:
        name: https://rpmfind.net/linux/centos/7.9.2009/os/x86_64/Packages/libmaxminddb-1.2.0-6.el7.x86_64.rpm
      when: "'libmaxminddb' not in packages['results']"
